# rule identifiers to opt in
opt_in_rules:
  - implicit_return
  - fatal_error_message
  - empty_count
  - force_unwrapping
  - private_action
  - private_outlet
  - private_over_fileprivate
  - strong_iboutlet
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets 
  - multiline_parameters
  - multiline_parameters_brackets
  
disabled_rules:
  - todo

force_cast: 
  severity: warning
force_try: 
  severity: warning

excluded:
  - Pods
  - Tests
  - fastlane
  - Configuration
  - bundle/vendors
# special configuration for rules
large_tuple:
  warning: 2
  error: 3

file_length:
  warning: 400
  error: 1000

nesting:
    type_level: 2

function_body_length:
  warning: 40
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: false

function_parameter_count:
  warning: 5
  error: 8

colon:
  flexible_right_spacing: false
  apply_to_dictionaries: true

line_length:
  warning: 120
  error: 200
  ignores_urls: false
  ignores_function_declarations: false
  ignores_comments: false

identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: [id, x, y, v, dx, dy, vc, i, k, j]

type_name:
  min_length:
    error: 3
  excluded: [UI]
